chacao-investimentos/config/routes.rb
Rails.application.routes.draw do
  resources :application_dts, only: [:create, :show, :new,:destroy]
  resources :application_ifs, only: [:create, :show, :new,:destroy]
  resources :application_fis, only: [:create, :show, :new,:destroy]
  resources :fixed_incomes, only: [:create, :show, :new,:destroy]
  resources :investment_funds, only: [:create, :show, :new,:destroy]
  resources :direct_treasures, only: [:create, :show, :new,:destroy]
  root 'application#landing'

  resources :users

  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout

  get '/products', to: 'products#index', as: :products

  get '/applications', to: 'applications#index', as: :applications

  get '/direct_treasures/:id', to: 'direct_treasures#show', as: :show_direct_treasure
  get '/fixed_incomes/:id', to: 'fixed_incomes#show', as: :show_fixed_income
  get '/investment_funds/:id', to: 'investment_funds#show', as: :show_investment_fund
  post '/application_fis/new', to: 'application_fis#create'
  post '/application_dts/new', to: 'application_dts#create'
  post '/application_ifs/new', to: 'application_ifs#create'
end

chacao-investimentos/app/models/fixed_income.rb
class FixedIncome < ApplicationRecord
  has_many :application_fis, dependent: :destroy
end

chacao-investimentos/app/controllers/fixed_incomes_controller.rb
class FixedIncomesController < ApplicationController
  before_action :set_fixed_income, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:destroy, :new, :create]

  # GET /fixed_incomes
  # GET /fixed_incomes.json
  def index
    @fixed_incomes = FixedIncome.all
  end

  # GET /fixed_incomes/1
  # GET /fixed_incomes/1.json
  def show
  end

  # GET /fixed_incomes/new
  def new
    @fixed_income = FixedIncome.new
  end

  # GET /fixed_incomes/1/edit
  def edit
  end

  # POST /fixed_incomes
  # POST /fixed_incomes.json
  def create
    @fixed_income = FixedIncome.new(fixed_income_params)

    respond_to do |format|
      if @fixed_income.save
        format.html { redirect_to @fixed_income, notice: 'Fixed income was successfully created.' }
        format.json { render :show, status: :created, location: @fixed_income }
      else
        format.html { render :new }
        format.json { render json: @fixed_income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fixed_incomes/1
  # PATCH/PUT /fixed_incomes/1.json
  def update
    respond_to do |format|
      if @fixed_income.update(fixed_income_params)
        format.html { redirect_to @fixed_income, notice: 'Fixed income was successfully updated.' }
        format.json { render :show, status: :ok, location: @fixed_income }
      else
        format.html { render :edit }
        format.json { render json: @fixed_income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixed_incomes/1
  # DELETE /fixed_incomes/1.json
  def destroy
    @fixed_income.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Fixed income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fixed_income
      @fixed_income = FixedIncome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fixed_income_params
      params.require(:fixed_income).permit(:category, :entity, :due_date, :time_limit, :tax)
    end
end

chacao-investimentos/app/helpers/fixed_incomes_helper.rb
module FixedIncomesHelper
end

chacao-investimentos/app/views/fixed_incomes/_form.html.erb
<%= form_with(model: fixed_income, local: true) do |form| %>
  <% if fixed_income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fixed_income.errors.count, "error") %> prohibited this fixed_income from being saved:</h2>

      <ul>
        <% fixed_income.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-size">
    <div class="pt-5 form-row justify-content-around">
      <div class="form-group col-md-5">
        <%= form.label :entity, "Nome da Entidade Emissora" %>
        <%= form.text_field :entity, class: "form-control", required: true %>
      </div>
      <div class="form-group col-md-5">
        <%= form.label :category, "Classe" %>
        <%= form.select :category, options_for_select(["CDB", "LCA", "LCI", "LF", "LC"]), {}, class: "form-control", required: true %>
      </div>
    </div>

    <div class="pt-5 form-row justify-content-around">
      <div class="form-group col-md-5">
        <%= form.label :due_date, "Prazo de Vencimento" %>
        <%= form.number_field :due_date, {min: 0, class: "form-control", required: true} %>
      </div>

      <div class="form-group col-md-5">
        <%= form.label :tax, "Taxa de Remuneração (%)" %>
        <%= form.number_field :tax, {min: 0, step: 0.01, class: "form-control", required: true} %>
      </div>
    </div>

    <div class="pt-5 form-row justify-content-around">

      <div class="form-group col-md-5">
        <%= form.label :value, "Valor mínimo" %>
        <%= form.number_field :value, {min: 0, step: 0.01, class: "form-control", required: true} %>
      </div>

      <div class="form-group col-md-5">
        <%= form.label :time_limit, "Horário limite" %>
        <%= form.time_field :time_limit, class: "form-control", required: true %>
      </div>

    </div>

    <div class="form-row justify-content-center pt-5">
      <div class="pr-1">
        <%= form.submit "Criar", class: "btn btn-color" %>
      </div>
      <div class="pl-1">
        <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
      </div>
    </div>
  </div>
<% end %>

chacao-investimentos/app/views/fixed_incomes/new.html.erb
  <div class="col pb-4">
    <h1 class="border-bottom border-dark col pb-4 pt-3"> Criar Renda Fixa</h1>
  </div>

<%= render 'form', fixed_income: @fixed_income %>

chacao-investimentos/app/views/fixed_incomes/show.html.erb
<div class="col pb-4">
  <h1 class="border-bottom border-dark col pb-4 pt-3"> Renda Fixa </h1>
</div>

<div class="text-size">
  <div class="padding-header form-row justify-content-around">
    <div class="col-md-5 d-flex flex-column">
      <p>Nome da Entidade Emissora</p>
      <p class="text-center text-secondary">
        <%= @fixed_income.entity %>
      </p>
    </div>

    <div class="col-md-5 d-flex flex-column">
      <p>Classe</p>
      <p class="text-center text-secondary">
        <%= @fixed_income.category %>
      </p>
    </div>
  </div>

  <div class="pt-5 form-row justify-content-around">
    <div class="col-md-5 d-flex flex-column">
      <p>Prazo de Vencimento</p>
      <p class="text-center text-secondary">
        <%= @fixed_income.due_date %>
      </p>
    </div>

    <div class="col-md-5 d-flex flex-column">
      <p>Taxa de Remuneração</p>
      <p class="text-center text-secondary">
        <%= @fixed_income.tax %>
      </p>
    </div>
  </div>

  <div class="pt-5 form-row justify-content-around">
    <div class="col-md-5 d-flex flex-column">
      <p>Valor Mínimo</p>
      <p class="text-center text-secondary">
        <%= number_to_currency(@fixed_income.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
      </p>
    </div>

    <div class="col-md-5 d-flex flex-column">
      <p>Horário Limite</p>
      <p class="text-center text-secondary">
        <%= @fixed_income.time_limit.strftime("%H:%M") %>
      </p>
    </div>
  </div>

  <% if current_user&.is_admin? %>
    <div class="form-row justify-content-center pt-5">
      <div class="pr-1">
        <%= link_to 'Excluir', @fixed_income, class: "btn btn-color", method: :delete, data: {confirm: 'Você tem certeza?'} %>
      </div>
      <div class="pl-1">
        <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
      </div>
    </div>
  <% elsif current_user %>
    <div class="form-row justify-content-center pt-5">
      <div class="pr-1">
        <button type="button" class="btn btn-color" data-toggle="modal" data-target="#application-fi">
          Realizar aplicação
        </button>
        <%= render 'layouts/modal', object: @fixed_income, name: @fixed_income.entity, url: new_application_fi_path, is_dt: false %>
      </div>
      <div class="pl-1">
        <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
      </div>
    </div>
  <% else %>
    <div class="form-row justify-content-center pt-5">
      <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
    </div>
  <% end %>

</div>