chacao-investimentos/config/routes.rb
Rails.application.routes.draw do
  resources :application_dts, only: [:create, :show, :new,:destroy]
  resources :application_ifs, only: [:create, :show, :new,:destroy]
  resources :application_fis, only: [:create, :show, :new,:destroy]
  resources :fixed_incomes, only: [:create, :show, :new,:destroy]
  resources :investment_funds, only: [:create, :show, :new,:destroy]
  resources :direct_treasures, only: [:create, :show, :new,:destroy]
  root 'application#landing'

  resources :users

  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout

  get '/products', to: 'products#index', as: :products

  get '/applications', to: 'applications#index', as: :applications

  get '/direct_treasures/:id', to: 'direct_treasures#show', as: :show_direct_treasure
  get '/fixed_incomes/:id', to: 'fixed_incomes#show', as: :show_fixed_income
  get '/investment_funds/:id', to: 'investment_funds#show', as: :show_investment_fund
  post '/application_fis/new', to: 'application_fis#create'
  post '/application_dts/new', to: 'application_dts#create'
  post '/application_ifs/new', to: 'application_ifs#create'
end

chacao-investimentos/app/models/direct_treasure.rb
class DirectTreasure < ApplicationRecord
  has_many :application_dts, dependent: :destroy
end

chacao-investimentos/app/controllers/direct_treasures_controller.rb
class DirectTreasuresController < ApplicationController
  before_action :set_direct_treasure, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:destroy, :new, :create]

  # GET /direct_treasures
  # GET /direct_treasures.json
  def index
    @direct_treasures = DirectTreasure.all
  end

  # GET /direct_treasures/1
  # GET /direct_treasures/1.json
  def show
  end

  # GET /direct_treasures/new
  def new
    @direct_treasure = DirectTreasure.new
  end

  # GET /direct_treasures/1/edit
  def edit
  end

  # POST /direct_treasures
  # POST /direct_treasures.json
  def create
    @direct_treasure = DirectTreasure.new(direct_treasure_params)

    respond_to do |format|
      if @direct_treasure.save
        format.html { redirect_to @direct_treasure, notice: 'Direct treasure was successfully created.' }
        format.json { render :show, status: :created, location: @direct_treasure }
      else
        format.html { render :new }
        format.json { render json: @direct_treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direct_treasures/1
  # PATCH/PUT /direct_treasures/1.json
  def update
    respond_to do |format|
      if @direct_treasure.update(direct_treasure_params)
        format.html { redirect_to @direct_treasure, notice: 'Direct treasure was successfully updated.' }
        format.json { render :show, status: :ok, location: @direct_treasure }
      else
        format.html { render :edit }
        format.json { render json: @direct_treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direct_treasures/1
  # DELETE /direct_treasures/1.json
  def destroy
    @direct_treasure.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Direct treasure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direct_treasure
      @direct_treasure = DirectTreasure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def direct_treasure_params
      params.require(:direct_treasure).permit(:index, :name, :due_date, :tax, :value)
    end
end

chacao-investimentos/app/helpers/direct_treasures_helper.rb
module DirectTreasuresHelper
end

chacao-investimentos/app/views/direct_treasures/_form.html.erb
<%= form_with(model: direct_treasure, local: true) do |form| %>
  <% if direct_treasure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(direct_treasure.errors.count, "error") %> prohibited this direct_treasure from being saved:</h2>

      <ul>
        <% direct_treasure.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-size">
    <div class="padding-header form-row justify-content-around">
      <div class="form-group col-md-5">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>
      <div class="form-group col-md-5">
        <%= form.label :index, "Indexador" %>
        <%= form.select :index, options_for_select(["IPCA","SELIC","Prefixado"]), {}, class: "form-control", required: true %>
      </div>
    </div>

    <div class="pt-5 form-row justify-content-around">
      <div class="form-group col-md-5">
        <%= form.label :tax, "Taxa (%)" %>
        <%= form.number_field :tax, {min: 0, step: 0.01, class: "form-control", required: true} %>
      </div>

      <div class="form-group col-md-5">
        <%= form.label :value, "Preço Unitário" %>
        <%= form.number_field :value, {min: 0, step: 0.01, class: "form-control", required: true} %>
      </div>
    </div>
    
    <div class="d-flex justify-content-center">
      <div class="due-date form-group pt-5 text-center">
        <%= form.label :due_date, "Data de Vencimento" %>
        <%= form.date_field :due_date, min: Date.today, value: Date.today, class: "form-control text-center", required: true %>
      </div>
    </div>

    <div class="form-row justify-content-center pt-5">
      <div class="pr-1">
        <%= form.submit "Criar", class: "btn btn-color" %>
      </div>
      <div class="pl-1">
        <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
      </div>
    </div>
  </div>
<% end %>

chacao-investimentos/app/views/direct_treasures/new.html.erb
<div class="col pb-4">
  <h1 class="border-bottom border-dark col pb-4 pt-3"> Criar Tesouro Direto</h1>
</div>

<%= render 'form', direct_treasure: @direct_treasure %>

chacao-investimentos/app/views/direct_treasures/show.html.erb
<div class="col pb-4">
  <h1 class="border-bottom border-dark col pb-4 pt-3"> Tesouro Direto</h1>
</div>

<div class="text-size">
  <div class="padding-header form-row justify-content-around">
    <div class="col-md-5 d-flex flex-column">
      <p>Nome</p>
      <p class="text-center text-secondary">
        <%= @direct_treasure.name %>
      </p>
    </div>

    <div class="col-md-5 d-flex flex-column">
      <p>Indexador</p>
      <p class="text-center text-secondary">
        <%= @direct_treasure.index %>
      </p>
    </div>
  </div>

  <div class="pt-5 form-row justify-content-around">
    <div class="col-md-5 d-flex flex-column">
      <p>Taxa</p>
      <p class="text-center text-secondary">
        <%= "#{@direct_treasure.tax} %" %>
      </p>
    </div>

    <div class="col-md-5 d-flex flex-column">
      <p>Preço Unitário</p>
      <p class="text-center text-secondary">
        <%= number_to_currency(@direct_treasure.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
      </p>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <div class="due-date pt-5 text-center">
      <p>Data de Vencimento</p>
      <p class="text-center text-secondary">
        <%= @direct_treasure.due_date.strftime("%d/%m/%Y") %>
      </p>
    </div>
  </div>

  <% if current_user&.is_admin? %>
    <div class="form-row justify-content-center pt-5">
      <div class="pr-1">
        <%= link_to 'Excluir', @direct_treasure, class: "btn btn-color", method: :delete, data: {confirm: 'Você tem certeza?'} %>
      </div>
      <div class="pl-1">
        <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
      </div>
    </div>
  <% elsif current_user %>
    <div class="form-row justify-content-center pt-5">
      <div class="pr-1">
        <button type="button" class="btn btn-color" data-toggle="modal" data-target="#application-fi">
          Realizar aplicação
        </button>
        <%= render 'layouts/modal', object: @direct_treasure, name: @direct_treasure.name, url: new_application_dt_path, is_dt: true %>
      </div>
      <div class="pl-1">
        <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
      </div>
    </div>
  <% else %>
    <div class="form-row justify-content-center pt-5">
      <%= link_to 'Voltar', products_path, class: "btn btn-color" %>
    </div>
  <% end %>
</div>