chacao-investimentos/config/routes.rb
Rails.application.routes.draw do
  resources :application_dts, only: [:create, :show, :new,:destroy]
  resources :application_ifs, only: [:create, :show, :new,:destroy]
  resources :application_fis, only: [:create, :show, :new,:destroy]
  resources :fixed_incomes, only: [:create, :show, :new,:destroy]
  resources :investment_funds, only: [:create, :show, :new,:destroy]
  resources :direct_treasures, only: [:create, :show, :new,:destroy]
  root 'application#landing'

  resources :users

  get '/login', to: 'user_sessions#new', as: :login
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy', as: :logout

  get '/products', to: 'products#index', as: :products

  get '/applications', to: 'applications#index', as: :applications

  get '/direct_treasures/:id', to: 'direct_treasures#show', as: :show_direct_treasure
  get '/fixed_incomes/:id', to: 'fixed_incomes#show', as: :show_fixed_income
  get '/investment_funds/:id', to: 'investment_funds#show', as: :show_investment_fund
  post '/application_fis/new', to: 'application_fis#create'
  post '/application_dts/new', to: 'application_dts#create'
  post '/application_ifs/new', to: 'application_ifs#create'
end

chacao-investimentos/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  belongs_to :account_type
end

chacao-investimentos/app/models/account_type.rb
class AccountType < ApplicationRecord
end

chacao-investimentos/app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

chacao-investimentos/app/models/application_dt.rb
class ApplicationDt < ApplicationRecord
  belongs_to :user
  belongs_to :direct_treasure
end

chacao-investimentos/app/models/application_fi.rb
class ApplicationFi < ApplicationRecord
  belongs_to :user
  belongs_to :fixed_income
end

chacao-investimentos/app/models/application_if.rb
class ApplicationIf < ApplicationRecord
  belongs_to :user
  belongs_to :investment_fund
end

chacao-investimentos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

chacao-investimentos/app/models/direct_treasure.rb
class DirectTreasure < ApplicationRecord
  has_many :application_dts, dependent: :destroy
end

chacao-investimentos/app/models/fixed_income.rb
class FixedIncome < ApplicationRecord
  has_many :application_fis, dependent: :destroy
end

chacao-investimentos/app/models/investment_fund.rb
class InvestmentFund < ApplicationRecord
  has_many :application_ifs, dependent: :destroy
end

chacao-investimentos/app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

chacao-investimentos/app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :phones, dependent: :destroy
  has_many :accounts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :application_fis, dependent: :destroy
  has_many :application_ifs, dependent: :destroy
  has_many :application_dts, dependent: :destroy
  accepts_nested_attributes_for :phones
  accepts_nested_attributes_for :accounts
  accepts_nested_attributes_for :addresses


  def phone
    phone = self.phones.first
    if phone
      "(#{phone.ddd}) #{phone.number}"
    end
  end
end

chacao-investimentos/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:filtered] == "true"
      filter
    else
      @direct_treasures = DirectTreasure.all
      @fixed_incomes = FixedIncome.all
      @investment_funds = InvestmentFund.all
    end
  end

  private

  def filter
    @direct_treasures = []
    @fixed_incomes = []
    @investment_funds = []

    unless params[:direct_treasure] == "0"
      @direct_treasures = DirectTreasure.all
    end
    unless params[:fixed_income] == "0"
      @fixed_incomes = FixedIncome.all
    end
    unless params[:investment_fund] == "0"
      @investment_funds = InvestmentFund.all
    end
  end
end

chacao-investimentos/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_your_self, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
    @user.phones.build
    @user.accounts.build
    @user.addresses.build
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.is_admin = false
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password, :name, :birth_date, :cpf,
                                 phones_attributes: [:id, :ddd, :number],
                                 accounts_attributes: [:id, :bank_code, :agency, :number, :account_type_id],
                                 address_attributes: [:id, :city, :state, :number, :complement, :cep, :neighbordhood])
  end
end

chacao-investimentos/app/helpers/application_helper.rb
module ApplicationHelper
end

chacao-investimentos/app/helpers/applications_helper.rb
module ApplicationsHelper
end

chacao-investimentos/app/helpers/direct_treasures_helper.rb
module DirectTreasuresHelper
end

chacao-investimentos/app/helpers/fixed_incomes_helper.rb
module FixedIncomesHelper
end

chacao-investimentos/app/helpers/products_helper.rb
module ProductsHelper
end

chacao-investimentos/app/helpers/users_helper.rb
module UsersHelper
end

chacao-investimentos/app/views/addresses/_fields.html.erb
<div class="form-row">
  <div class="form-group col">
    <%= f.label :cep, 'CEP' %>
    <%= f.text_field :cep, {maxlength: 10, class: 'form-control', required: true}  %>
  </div>
  <div class="form-group col">
    <%= f.label 'Estado' %>
    <%= f.text_field :state, class: 'form-control', required: true  %>
  </div>
</div>
<div class="form-row">
  <div class="form-group col">
    <%= f.label 'Cidade' %>
    <%= f.text_field :city, class: 'form-control', required: true  %>
  </div>
  <div class="form-group col">
    <%= f.label 'Bairro' %>
    <%= f.text_field :neighbordhood, class: 'form-control', required: true  %>
  </div>
</div>
<div class="form-row">
  <div class="form-group col">
    <%= f.label 'Logradouro' %>
    <%= f.text_field :complement, class: 'form-control', required: true  %>
  </div>
  <div class="form-group col">
    <%= f.label 'Número' %>
    <%= f.number_field :number, {min: 0, max: 999, class: 'form-control', required: true}  %>
  </div>
</div>

chacao-investimentos/app/views/addresses/_show.html.erb
<div class="form-row">
  <div class="form-group col">
    <h4> CEP </h4>
    <p><%= address.cep %></p>
  </div>
  <div class="form-group col">
    <h4> Estado </h4>
    <p><%= address.state %></p>
  </div>
</div>
<div class="form-row">
  <div class="form-group col">
    <h4> Cidade </h4>
    <p><%= address.city %></p>
  </div>
  <div class="form-group col">
    <h4> Bairro </h4>
    <p><%= address.neighboorhood %></p>
  </div>
</div>
<div class="form-row">
  <div class="form-group col">
    <h4> Logradouro </h4>
    <p><%= address.complement %></p>
  </div>
  <div class="form-group col">
    <h4> Número </h4>
    <p><%= address.number %></p>
  </div>
</div>

chacao-investimentos/app/views/layouts/_dt-card.html.erb
<div class="p-3">
  <div class="card h-100 product-card shadow-sm">
    <div class="card-body d-flex flex-column justify-content-around" id="card-body">
      <%= link_to show_direct_treasure_path(direct_treasure), class: "product-title text-center" do %>
        <h5 class="card-title max-lines-2"><%= direct_treasure.name %></h5>
      <% end %>
      <h5 class="card-title d-flex justify-content-center">Tesouro Direto</h5>
      <div class="d-flex justify-content-center">
        <%= link_to show_direct_treasure_path(direct_treasure), class: "btn btn-color w-50" do %>
          <span><strong><%= number_to_currency(direct_treasure.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></strong></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

chacao-investimentos/app/views/layouts/_fi-card.html.erb
<div class="p-3">
  <div class="card h-100 product-card shadow-sm">
    <div class="card-body d-flex flex-column justify-content-around" id="card-body">
      <%= link_to show_fixed_income_path(fixed_income), class: "product-title text-center" do %>
        <h5 class="card-title max-lines-2"><%= fixed_income.entity %></h5>
      <% end %>
      <h5 class="card-title d-flex justify-content-center"> Renda Fixa </h5>
      <div class="d-flex justify-content-center">
        <%= link_to show_fixed_income_path(fixed_income), class: "btn btn-color w-50" do %>
          <span><strong><%= number_to_currency(fixed_income.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></strong></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

chacao-investimentos/app/views/layouts/_if-card.html.erb
<div class="p-3">
  <div class="card h-100 product-card shadow-sm">
    <div class="card-body d-flex flex-column justify-content-around" id="card-body">
      <%= link_to show_investment_fund_path(investment_fund), class: "product-title text-center" do %>
        <h5 class="card-title max-lines-2"><%= investment_fund.name %></h5>
      <% end %>
      <h5 class="card-title d-flex justify-content-center">Fundo de Investimento</h5>
      <div class="d-flex justify-content-center">
        <%= link_to show_investment_fund_path(investment_fund), class: "btn btn-color w-50" do %>
          <span><strong> <%= number_to_currency(investment_fund.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></strong></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

chacao-investimentos/app/views/layouts/_modal.html.erb
<div class="modal fade" id="application-fi" tabindex="-1" role="dialog" aria-labelledby="application-fi-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="application-fi-title">
          Aplicação em <%= name %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: url, method: :post, local: true do |f| %>
        <%= f.hidden_field :object_id, value: object.id %>
        <% unless is_dt %>
          <div class="modal-body px-2">
            <div class="mx-0 form-group row justify-content-center">
              <%= f.label :value, 'Valor', class: 'col-sm-2 col-form-label text-dark' %>
              <div class="col-sm-8 form-group">
                <%= f.number_field :value, {min: object.value, step: 0.01, class: 'form-control', required: true} %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="modal-body px-2">
            <div class="mx-0 form-group col">
              <%= f.label :quantity, 'Quantidade', class: 'col-sm-2 col-form-label text-dark' %>
              <div class="form-group">
                <%= f.number_field :quantity, {min: 0, class: 'form-control', required: true} %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="modal-footer">
          <button type="button" class="btn btn-color" data-dismiss="modal">Fechar</button>
          <%= f.submit "Finalizar", class: "btn btn-color" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

chacao-investimentos/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <% if current_user %>
    <a class="d-flex align-items-center navbar-brand" href="<%= url_for products_path %>">
      <i class="fas fa-chart-line fa-2x"></i>
      <span class="pl-3 mr-3">Chacão Investimentos</span>
    </a>
  <% else %>
    <a class="d-flex align-items-center navbar-brand" href="<%= url_for root_path %>">
      <i class="fas fa-chart-line fa-2x"></i>
      <span class="pl-3 mr-3">Chacão Investimentos</span>
    </a>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav right">
      <% if current_user %>
        <%= link_to "Perfil", user_path(current_user), class: 'nav-item nav-link' %>
        <%= link_to "Logout", logout_path, class: 'nav-item nav-link', method: :delete %>
      <% else %>
        <%= link_to "Login", login_path, class: 'nav-item nav-link' %>
        <%= link_to "Cadastrar", new_user_path, class: 'nav-item nav-link' %>
      <% end %>
    </div>
  </div>
</nav>

chacao-investimentos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>Chacão Investimentos</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
<%= render 'layouts/navbar' %>
<div class="content">
  <%= yield %>
</div>
</body>
</html>